const NimboraLayers={map:null,radar:null,marker:null,points:null,mode:'map',frames:[],frame:0};
const RV='https://api.rainviewer.com/public/weather-maps.json',WX='https://api.open-meteo.com/v1/forecast';
const layerLabels={map:'Street map',rain:'Rain radar',wind:'Wind',thunder:'Thunderstorms',cyclone:'Severe storm / cyclone risk'};
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function tilePoint(lat,lon,z){const n=2**z,x=Math.floor((lon+180)/360*n),y=Math.floor((1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2*n);return{x,y}}
function ensureMap(){const el=document.querySelector('#interactiveMap');const p=window.nimboraGetPlace?.();if(!el||!p||!window.L)return;if(NimboraLayers.map)NimboraLayers.map.remove();el.innerHTML='';el.classList.add('leaflet-ready');const map=L.map(el,{zoomControl:false,attributionControl:true}).setView([p.latitude,p.longitude],8);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);NimboraLayers.map=map;NimboraLayers.marker=L.circleMarker([p.latitude,p.longitude],{radius:7,weight:2,fillOpacity:.9}).addTo(map).bindPopup(`<b>${p.name||'Selected location'}</b>`);setTimeout(()=>map.invalidateSize(),100);applyLayer('map')}
async function radar(){if(!NimboraLayers.map)return;try{const d=await fetch(RV,{cache:'no-store'}).then(r=>r.json());NimboraLayers.frames=d.radar?.past||[];NimboraLayers.frame=Math.max(0,NimboraLayers.frames.length-1);if(NimboraLayers.radar)NimboraLayers.map.removeLayer(NimboraLayers.radar);const f=NimboraLayers.frames[NimboraLayers.frame];if(!f)throw Error('No radar frame');NimboraLayers.radar=L.tileLayer(`https://tilecache.rainviewer.com${f.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity:.65,maxZoom:12,zIndex:500,attribution:'Radar © RainViewer'}).addTo(NimboraLayers.map);setStatus(`Rain radar · ${new Date(f.time*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`)}catch(e){console.error(e);setStatus('Rain radar temporarily unavailable')}}
async function grid(){const p=window.nimboraGetPlace?.();if(!p||!NimboraLayers.map)return;const latStep=1.2,lonStep=1.2,pts=[];for(let a=-2;a<=2;a++)for(let b=-2;b<=2;b++)pts.push([+(p.latitude+a*latStep).toFixed(3),+(p.longitude+b*lonStep).toFixed(3)]);const lat=pts.map(x=>x[0]).join(','),lon=pts.map(x=>x[1]).join(',');const u=new URL(WX);u.search=new URLSearchParams({latitude:lat,longitude:lon,timezone:'auto',current:'precipitation,rain,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m'});try{const d=await fetch(u).then(r=>r.json());const arr=d.current?Array.isArray(d.current)?d.current:[d.current]:[];if(!arr.length)throw Error('grid response unavailable');NimboraLayers.points=arr;drawGrid(arr)}catch(e){console.error(e);setStatus('Weather layer unavailable')}}
function drawGrid(arr){if(!NimboraLayers.map)return;const p=window.nimboraGetPlace?.();if(NimboraLayers.pointsLayer)NimboraLayers.map.removeLayer(NimboraLayers.pointsLayer);const g=L.layerGroup();arr.forEach((x,i)=>{const lat=x.latitude??x.lat,lon=x.longitude??x.lon;if(lat==null||lon==null)return;const rain=Number(x.rain??x.precipitation??0),wind=Number(x.wind_speed_10m??0),gust=Number(x.wind_gusts_10m??0),code=Number(x.weather_code??0);let show=NimboraLayers.mode==='rain'?rain>0.05:NimboraLayers.mode==='wind'?wind>=10:NimboraLayers.mode==='thunder'?(code>=95):NimboraLayers.mode==='cyclone'?(gust>=63||wind>=63||code>=95):false;if(!show)return;let value,label;if(NimboraLayers.mode==='rain'){value=Math.min(100,Math.max(10,rain*25));label=`Rain ${rain.toFixed(1)} mm`;}else if(NimboraLayers.mode==='wind'){value=Math.min(100,wind);label=`Wind ${Math.round(wind)} km/h · Gust ${Math.round(gust)} km/h`;}else if(NimboraLayers.mode==='thunder'){value=code>=95?90:0;label='Thunderstorm risk';}else{value=Math.min(100,Math.max(50,gust));label=`Severe storm risk · gust ${Math.round(gust)} km/h`;}const c=L.circleMarker([lat,lon],{radius:NimboraLayers.mode==='wind'?Math.max(8,Math.min(18,wind/2)):Math.max(7,value/9),weight:1,fillOpacity:.45}).bindTooltip(`${label}<br>Code ${code}`,{direction:'top'});if(NimboraLayers.mode==='wind'){const icon=L.divIcon({className:'wind-marker',html:`<span style="transform:rotate(${Number(x.wind_direction_10m||0)}deg)">➤</span><b>${Math.round(wind)}</b>`,iconSize:[50,30],iconAnchor:[25,15]});L.marker([lat,lon],{icon,interactive:true}).bindTooltip(label).addTo(g)}else c.addTo(g)});NimboraLayers.pointsLayer=g.addTo(NimboraLayers.map)}
async function applyLayer(mode){NimboraLayers.mode=mode;document.querySelectorAll('[data-weather-layer]').forEach(b=>b.classList.toggle('active',b.dataset.weatherLayer===mode));if(NimboraLayers.radar){NimboraLayers.map.removeLayer(NimboraLayers.radar);NimboraLayers.radar=null}if(NimboraLayers.pointsLayer){NimboraLayers.map.removeLayer(NimboraLayers.pointsLayer);NimboraLayers.pointsLayer=null}setStatus(layerLabels[mode]||'Weather layer');if(mode==='rain')return radar();if(['wind','thunder','cyclone'].includes(mode))return grid()}
function setStatus(s){const x=document.querySelector('#interactiveMapStatus');if(x)x.textContent=s}
async function initLayers(){try{await loadLeaflet();ensureMap();document.querySelectorAll('[data-weather-layer]').forEach(b=>b.onclick=()=>applyLayer(b.dataset.weatherLayer));document.querySelector('#mapZoomIn')?.addEventListener('click',()=>NimboraLayers.map?.zoomIn());document.querySelector('#mapZoomOut')?.addEventListener('click',()=>NimboraLayers.map?.zoomOut());document.querySelector('#mapReset')?.addEventListener('click',()=>{const p=window.nimboraGetPlace?.();if(p)NimboraLayers.map?.flyTo([p.latitude,p.longitude],8)});document.querySelector('#leafletLocate')?.addEventListener('click',()=>{const p=window.nimboraGetPlace?.();if(p)NimboraLayers.map?.flyTo([p.latitude,p.longitude],10)});window.nimboraWeatherLayers={refresh:ensureMap,apply:applyLayer}}catch(e){console.error(e);setStatus('Interactive map unavailable')}}
document.addEventListener('DOMContentLoaded',initLayers);